resources:
  - name: pbag
    type: PropertyBag
    configuration:
      tfFileName: latest


pipelines:
  - name: affinity_with_resource
    steps:
      - name: first_step
        type: Bash
        configuration:
          affinityGroup: test_affinity
          integrations:
            - name: demoArt
          outputResources:
            - name: pbag
        execution:
          onExecute:
            - echo "${run_number}" > tfFile-${run_number}.txt
            - jfrog rt u tfFile-${run_number}.txt generic-local
            - write_output pbag "tfFileName=tfFile-${run_number}.txt"
      - name: second_step
        type: Bash
        configuration:
          affinityGroup: test_affinity
          integrations:
            - name: demoArt          
          inputResources:
            - name: pbag
              trigger: false
        execution:
          onExecute:
            - jfrog rt dl generic-local/$res_pbag_tfFileName
            - cat $res_pbag_tfFileName
