resources:
  - name: pbag
    type: PropertyBag
    configuration:
      foo: bar


pipelines:
  - name: affinity_with_resource
    steps:
      - name: first_step
        type: Bash
        configuration:
          affinityGroup: test_affinity
          outputResources:
            - name: pbag
        execution:
          onExecute:
            - write_output myprops_affinity "hello=world${run_number}
      - name: second_step
        type: Bash
        configuration:
          affinityGroup: test_affinity
          inputResources:
            - name: pbag
              trigger: false
        execution:
          onExecute:
            - echo "hello is $hello"
