resources:
  - name: pbag
    type: PropertyBag
    configuration:
      foo: bar


pipelines:
  - name: affinity_with_resource
    steps:
      - name: first_step
        type: Bash
        configuration:
          affinityGroup: test_affinity
          integrations:
            - name: demoArt
          outputResources:
            - name: pbag
        execution:
          onExecute:
            - echo "${run_number}" > tfFile.txt
            - jfrog rt u tfFile.txt generic-local
            - write_output pbag "hello=world${run_number}"
      - name: second_step
        type: Bash
        configuration:
          affinityGroup: test_affinity
          integrations:
            - name: demoArt          
          inputResources:
            - name: pbag
              trigger: false
        execution:
          onExecute:
            - jfrog rt dl generic-local/tfFile.txt
            - cat tfFile.txt
